### ISSUE TITLE
wrong trackingCode field Value

### ISSUE THREAD

**Issue by christian71-stack** [timopaul/idealo-merchant-order-api-v2-php-sdk#1]
It becomes an incorrect string on SetFulfillmentInformation
{"carrier":"DHL","trackingCode":"[\"00340434287034152770\"]"}
Result is ErrorCode 400. Wrong Fieldvalue on Field: trackingCode

The Problem is the Double Encoding in HasParameters at addParameter:
After deactivate json_encode
{"carrier":"DHL","trackingCode":["00340434287034152770"]}

**Comment by timopaul** [comment]
Thank you for reporting. The problem has been fixed.
